### ISSUE TITLE
JDOM.Env Error

### ISSUE THREAD

**Issue by ayarrus** [stsourlidakis/selector-scrapper#1]
Capture:
![dont](https://user-images.githubusercontent.com/10744797/61962357-ad14e780-af9f-11e9-9b31-473eece4120a.png)

**Comment by stsourlidakis** [comment]
I've [updated](https://github.com/stsourlidakis/selector-scrapper/commit/a79ee19b4fd751c4f1ab0d0950bbc7be7b891ccb) the script to work with the latest version of jsdom, it should be fine now.

**Comment by LimaceHurlante** [comment]
![jsdom env is not a function](https://user-images.githubusercontent.com/45110475/121788813-a9f56580-cbd0-11eb-95ee-64168619a260.JPG)
Hello, it seems that jsdom.env is fully depretiated.
